package com.github.alex1304.ultimategdbot.utils;

import com.github.alex1304.ultimategdbot.core.UltimateGDBot;

import sx.blah.discord.handle.obj.IEmoji;

/**
 * Enumerates emojis available for the bot
 *
 * @author Alex1304
 */
public enum Emojis {
	ICON_NA,
	ICON_NA_FEATURED,
	ICON_NA_EPIC,
	ICON_EASY,
	ICON_EASY_FEATURED,
	ICON_EASY_EPIC,
	ICON_NORMAL,
	ICON_NORMAL_FEATURED,
	ICON_NORMAL_EPIC,
	ICON_HARD,
	ICON_HARD_FEATURED,
	ICON_HARD_EPIC,
	ICON_HARDER,
	ICON_HARDER_FEATURED,
	ICON_HARDER_EPIC,
	ICON_INSANE,
	ICON_INSANE_FEATURED,
	ICON_INSANE_EPIC,
	ICON_DEMON_EASY,
	ICON_DEMON_EASY_FEATURED,
	ICON_DEMON_EASY_EPIC,
	ICON_DEMON_MEDIUM,
	ICON_DEMON_MEDIUM_FEATURED,
	ICON_DEMON_MEDIUM_EPIC,
	ICON_DEMON_HARD,
	ICON_DEMON_HARD_FEATURED,
	ICON_DEMON_HARD_EPIC,
	ICON_DEMON_INSANE,
	ICON_DEMON_INSANE_FEATURED,
	ICON_DEMON_INSANE_EPIC,
	ICON_DEMON_EXTREME,
	ICON_DEMON_EXTREME_FEATURED,
	ICON_DEMON_EXTREME_EPIC,
	
	CREATOR_POINTS,
	DISLIKE,
	LIKE,
	DOWNLOADS,
	LENGTH,
	INFO,
	PLAY,
	SECRET_COIN,
	DEMON,
	USER_COIN,
	USER_COIN_UNVERIFIED,
	DIAMOND,
	STAR,
	GLOBAL_RANK,
	YOUTUBE,
	TWITTER,
	TWITCH,
	SUCCESS,
	FAILED,
	ELDER_MOD,
	MOD;
	
	public IEmoji get() {
		return UltimateGDBot.emoji(name().toLowerCase());
	}
	
	@Override
	public String toString() {
		return String.valueOf(get());
	}
}
