defaults: &defaults
    working_directory: ~/repo

cmd_build_beta: &cmd_build_beta
    run: mvn -Dultimategdbot.release.channel=beta package

cmd_build_stable: &cmd_build_stable
    run: mvn -Dultimategdbot.release.channel=stable package

version: 2

jobs:
    build_beta:
        <<: *defaults
        docker:
            - image: circleci/openjdk:8-jdk
        steps:
            - checkout
            - restore_cache:
                key: repo-{{ checksum "pom.xml" }}
            - run: mvn dependency:go-offline
            - save_cache:
                paths: ~/.m2
                key: repo-{{ checksum "pom.xml" }}
            - <<: *cmd_build_beta
            - store_test_results:
                path: target/surefire-reports
            - persist_to_workspace:
                root: target
                paths: ultimategdbot.jar
    deploy_beta:
        <<: *defaults
        machine:
            enabled: true
        steps:
            - attach_workspace:
                at: target
            - run: |
                ssh $SSH_USER@$SSH_HOST "mkdir -p ~/ultimategdbot ; pgrep -f ~/ultimategdbot/ultimategdbot-beta.jar | xargs kill -9"
                scp target/ultimategdbot.jar $SSH_USER@$SSH_HOST:~/ultimategdbot/ultimategdbot-beta.jar
                ssh $SSH_USER@$SSH_HOST "nohup java -jar ~/ultimategdbot/ultimategdbot-beta.jar >> out.log 2>&1 &"
    build_stable:
        <<: *defaults
        docker:
            - image: circleci/openjdk:8-jdk
        steps:
            - checkout
            - restore_cache:
                key: repo-{{ checksum "pom.xml" }}
            - run: mvn dependency:go-offline
            - save_cache:
                paths: ~/.m2
                key: repo-{{ checksum "pom.xml" }}
            - <<: *cmd_build_stable
            - store_test_results:
                path: target/surefire-reports
            - persist_to_workspace:
                root: target
                paths: ultimategdbot.jar
    deploy_stable:
        <<: *defaults
        machine:
            enabled: true
        steps:
            - attach_workspace:
                at: target
            - run: |
                ssh $SSH_USER@$SSH_HOST "mkdir -p ~/ultimategdbot ; pgrep -f ~/ultimategdbot/ultimategdbot-stable.jar | xargs kill -9"
                scp target/ultimategdbot.jar $SSH_USER@$SSH_HOST:~/ultimategdbot/ultimategdbot-stable.jar
                ssh $SSH_USER@$SSH_HOST "nohup java -jar ~/ultimategdbot/ultimategdbot-stable.jar >> out.log 2>&1 &"
workflows:
    version: 2
    build-deploy:
        jobs:
            build_beta:
                filters:
                    branches:
                        only: master
            deploy_beta:
                requires:
                    - build_beta
                filters:
                    branches:
                        only: master
            build_stable:
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /v.*/
            deploy_stable:
                requires:
                    - build_stable
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /v.*/