defaults: &defaults
    working_directory: ~/repo

cmd_build_beta: &cmd_build_beta
    run: >
        mvn
        -Dultimategdbot.release.channel="beta"
        -Dultimategdbot.prefix.full="ugdb?"
        -Dultimategdbot.prefix.canonical="u?"
        -Dhibernate.hikari.dataSource.url=$DB_URL_BETA
        -Dhibernate.hikari.dataSource.user=$DB_USER
        -Dhibernate.hikari.dataSource.password=$DB_PASSWORD
        -Dultimategdbot.client.id=$BOT_ID_BETA
        -Dultimategdbot.client.token=$BOT_TOKEN_BETA
        -Dultimategdbot.hierarchy.owner_id=$BOT_OWNER_ID
        -Dultimategdbot.hierarchy.official_guild_id=$BOT_OFFICIAL_GUILD_ID
        -Dultimategdbot.hierarchy.moderator_role_id=$BOT_MODERATOR_ROLE_ID
        -Dultimategdbot.gd_client.id=$BOT_GDACCOUNT_ID
        -Dultimategdbot.gd_client.password=$BOT_GDACCOUNT_PASSWORD
        -Dultimategdbot.misc.emoji_guild_id.1=$BOT_MISC_EMOJI_GUILD_ID_1
        -Dultimategdbot.misc.emoji_guild_id.2=$BOT_MISC_EMOJI_GUILD_ID_2
        package

cmd_build_stable: &cmd_build_stable
    run: >
        mvn
        -Dultimategdbot.release.channel="stable"
        -Dultimategdbot.prefix.full="ugdb!"
        -Dultimategdbot.prefix.canonical="u!"
        -Dhibernate.hikari.dataSource.url=$DB_URL
        -Dhibernate.hikari.dataSource.user=$DB_USER
        -Dhibernate.hikari.dataSource.password=$DB_PASSWORD
        -Dultimategdbot.client.id=$BOT_ID
        -Dultimategdbot.client.token=$BOT_TOKEN
        -Dultimategdbot.hierarchy.owner_id=$BOT_OWNER_ID
        -Dultimategdbot.hierarchy.official_guild_id=$BOT_OFFICIAL_GUILD_ID
        -Dultimategdbot.hierarchy.moderator_role_id=$BOT_MODERATOR_ROLE_ID
        -Dultimategdbot.gd_client.id=$BOT_GDACCOUNT_ID
        -Dultimategdbot.gd_client.password=$BOT_GDACCOUNT_PASSWORD
        -Dultimategdbot.misc.emoji_guild_id.1=$BOT_MISC_EMOJI_GUILD_ID_1
        -Dultimategdbot.misc.emoji_guild_id.2=$BOT_MISC_EMOJI_GUILD_ID_2
        package

version: 2

jobs:
    build_beta:
        <<: *defaults
        docker:
            - image: circleci/openjdk:8-jdk
        steps:
            - checkout
            - restore_cache:
                key: repo-{{ checksum "pom.xml" }}
            - run: mvn dependency:go-offline
            - save_cache:
                paths: ~/.m2
                key: repo-{{ checksum "pom.xml" }}
            - <<: *cmd_build_beta
            - store_test_results:
                path: target/surefire-reports
            - persist_to_workspace:
                root: target
                paths: ultimategdbot.jar
    deploy_beta:
        <<: *defaults
        machine:
            enabled: true
        steps:
            - attach_workspace:
                at: target
            - run: |
                ssh $SSH_USER@$SSH_HOST "mkdir -p ~/ultimategdbot ; pgrep -f ultimategdbot-beta. | xargs kill -9"
                scp target/ultimategdbot.jar $SSH_USER@$SSH_HOST:~/ultimategdbot/ultimategdbot-beta.jar
                ssh $SSH_USER@$SSH_HOST "nohup java -jar ~/ultimategdbot/ultimategdbot-beta.jar >> ~/ultimategdbot/out-beta.log 2>&1 &"
    build_stable:
        <<: *defaults
        docker:
            - image: circleci/openjdk:8-jdk
        steps:
            - checkout
            - restore_cache:
                key: repo-{{ checksum "pom.xml" }}
            - run: mvn dependency:go-offline
            - save_cache:
                paths: ~/.m2
                key: repo-{{ checksum "pom.xml" }}
            - <<: *cmd_build_stable
            - store_test_results:
                path: target/surefire-reports
            - persist_to_workspace:
                root: target
                paths: ultimategdbot.jar
    deploy_stable:
        <<: *defaults
        machine:
            enabled: true
        steps:
            - attach_workspace:
                at: target
            - run: |
                ssh $SSH_USER@$SSH_HOST "mkdir -p ~/ultimategdbot ; pgrep -f ultimategdbot-stable | xargs kill -9"
                scp target/ultimategdbot.jar $SSH_USER@$SSH_HOST:~/ultimategdbot/ultimategdbot-stable.jar
                ssh $SSH_USER@$SSH_HOST "nohup java -jar ~/ultimategdbot/ultimategdbot-stable.jar >> ~/ultimategdbot/out-stable.log 2>&1 &"
workflows:
    version: 2
    build-deploy:
        jobs:
            - build_beta:
                filters:
                    branches:
                        only: master
            - deploy_beta:
                requires:
                    - build_beta
                filters:
                    branches:
                        only: master
            - build_stable:
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /v.*/
            - deploy_stable:
                requires:
                    - build_stable
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /v.*/